astyle src/*.cpp src/*.h ^
    --add-braces ^
    --align-pointer=type ^
    --align-reference=type ^
    --attach-classes ^
    --attach-closing-while ^
    --attach-inlines ^
    --attach-namespaces ^
    --close-templates ^
    --convert-tabs ^
    --indent-classes ^
    --indent-modifiers ^
    --indent-namespaces ^
    --indent-preproc-define ^
    --indent-switches ^
    --indent=spaces=4 ^
    --lineend=linux ^
    --pad-comma ^
    --pad-header ^
    --pad-include ^
    --pad-negation ^
    --pad-oper ^
    --squeeze-ws ^
    --style=allman ^
    --suffix=none ^
    --unpad-paren